# -*- coding: utf-8 -*-
"""Proctor_HOE12-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwhthN1ko_bZEF2YWT7Q6u5huCXIV-2O

# **HOE12**

**HOE 12.2**
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

#HOE 12.2

import streamlit as st

st.title("Oklahoma State University")
st.markdown("""
1. Mascot: Pistol Pete
2. Colors: Orange and Black
""")
st.markdown("""
- Location: Stillwater, Oklahoma
""")
st.markdown("[Visit OSU Website](https://okstate.edu) for more info.")